### ISSUE TITLE
 C. L. Andrews photographs, 1880s-1948 (clarence-andrews)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#1]
**Item Count:** 41 items

**Item Types:** Image

**Access Restrictions:**

**Complex Objects:**

**pid List:** 
https://github.com/OregonDigital/OD2-migration/blob/master/clarence-andrews/pids.txt

**Comment by lsat12357** [comment]
prefight errors required making updates to the crosswalk_overrides 
see https://github.com/OregonDigital/OD2/compare/feature/update-crosswalk-clarence-andrews-preflight
and fixing two fields that needed to be moved: captionTItle to alternative and earliestDate/latestDate to viewDate

**Comment by lsat12357** [comment]
reran preflight and looks good to move on

**Comment by luisgreg99** [comment]
Verification status: pass!

**Comment by lsat12357** [comment]
Restricted items: 0
Compound items: 0

**Comment by sseymore** [comment]
Left off at QA; need to find a way to QA unreviewed assets in the search interface with admin permissions/new account or get added to appropriate admin sets
