### ISSUE TITLE
1993 ODFW Oregon Rocky Shore Aerial Photography Survey (rockyshore93)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#104]
**Item Count:** 300 items

**Item Types:** Image

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/rockyshore93/rockyshore93_pids.txt

**Comment by wickr** [comment]
Had a slash in the `full` predicate like Braceros did, so I fixed that and am redoing the export.

**Comment by wickr** [comment]
Ingest looks good, verifier and label verifier came back clean

**Comment by carakey** [comment]
**QA**

Overall:

- [ ]   All works are migrated- original number of works and OD2 works match (Migration)
- [ ]   Check that a minimum of 5 works are accessible in browse everything/all
- [ ]   Check that a minimum of 5 works are accessible in by clicking on them in browse everything/all
- [ ]   If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible.
- [ ]   Confirm works are in the correct Admin set.

Search/indexing/faceting check:

- [ ]   Works and collections appear in browse everything/all when searched with corresponding metadata
- [ ]   Thumbnails are appearing for works; the collection has the correct icon.
- [ ]   Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:

- [ ]   Controlled and uncontrolled facets appear and are populated by data from works (When checking facets, check the core facets in the search results and the collection-specific facets on the collection homepage.)
- [ ]   Labels are fetching correctly
- [ ]   URIs are resolving correctly

Work pages:

- [ ] The digital object(s) appear in viewer
- Files are attached
- Derivatives were created (both automated check from Migration and visual check from Metadeities)
- [ ] Metadata is also there in work and viewer
- Collection information is also on work page
- Confirm metadata is in IIIF viewer
- [ ] Linked Data:
- Labels are fetching correctly
- URIs are resolving correctly
- [ ] Download
- If high res download, double-check
- [ ] Copyright
- Confirm copyright logo matches statement

Collection pages:

- [ ]   Collection pages are there
- [ ]   Collection description/blurb is there
- [ ]   Facets are there
- [ ]   Restrictions: Double-check restricted collections and works (VPN)
- [ ]   Bulk Approve (step 11)
- [ ]   Collection-level QA: Compare number of assets on OD2 with total in original pidlist (step 12)

**Comment by carakey** [comment]
QA Fail. Publisher facet present for collection in OD1 but missing in OD2.

**Comment by carakey** [comment]
Also, date_created is confusing in this collection. The photos were taken in 1993, which is entered as Date, but they also all have a Created date in 2008. In gallery view of collection browse, the dates are displayed as '1993-2008' under the thumbnails. In the Decade facet they all appear in both '1990-1999' and '2000-2009'. It's not a migration issue but wanted to check this functionality and/or suggest remediating the collection.

**Comment by wickr** [comment]
Publisher facet I'm seeing now? On the coll homepage: https://prod.oregondigital.org/collections/rockyshore93?locale=en#content
May have been a fetching or indexing issue that resolved itself.

Agree about the Date Created confusion, I'll remediate in OD1 and then update the metadata here.

**Comment by wickr** [comment]
Date Created was remediated in OD1 (moved to dateSubmitted, which is currently logged in the migrator works but not used directly), metadata re-exported, and updated in OD2. Everything looks correct now, such as the date on Gallery view being only 1993: https://prod.oregondigital.org/catalog?f%5Bnon_user_collections_ssim%5D%5B%5D=rockyshore93&locale=en&view=gallery#content

**Comment by carakey** [comment]
@wickr I'm not seeing the Locations on these, do they need to be reindexed?

**Comment by wickr** [comment]
oh good catch. The uris are all `http`. I think when I re-exported metadata I must've left off the geonames fix flag. I'll have to do it again.

**Comment by wickr** [comment]
Ok, Location URIs have been fixed, and all seem to be good now.

**Comment by carakey** [comment]
@wickr These look good, ready for bulk approve

**Comment by wickr** [comment]
Bulk approval completed. No recent edits or additions to this collection.
