### ISSUE TITLE
osu-historical-images_am

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#1056]
**Item Count:** 500 items

**Item Types:** Image/Document

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/osu-historical-images/osu-historical-images_am.txt

**Parent:** https://github.com/OregonDigital/OD2-migration/issues/1043

**Comment by KevinJonesMeta** [comment]
QA pass. Ready for bulk review.

**Comment by wickr** [comment]
All are reviewed and counts are looking good.
