### ISSUE TITLE
osu-baseball_ac

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#108]
**Item Count:** 500 items

**Item Types:** Image/Document/Audio/Video/Generic

**Access Restrictions:**

**Complex Objects:**

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/osu-baseball/osu-baseball_ac.txt

#105

**Comment by KevinJonesMeta** [comment]
QA Pass. Batch ready for bulk approval.

**Comment by wickr** [comment]
One work in this batch has no content file in OD1, so still has verification/label issues. Everything else is good.

5712m685p
