### ISSUE TITLE
osu-baseball_ad

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#109]
**Item Count:** 137 items

**Item Types:** Image/Document/Audio/Video/Generic

**Access Restrictions:**

**Complex Objects:**

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/osu-baseball/osu-baseball_ad.txt

#105

**Comment by wickr** [comment]
Verification report was clean.

**Comment by KevinJonesMeta** [comment]
QA Pass. It appears all of OSU Baseball Centennial set is in OD2 so I couldn't isolate just these 137 in the dashboard. I approved 5 from the pid list to test, but I reviewed 4 other works from the full set before I noticed.

**Comment by wickr** [comment]
Confirmed again there's no verification issues with this batch.
