### ISSUE TITLE
aerial-photos-mid-willamette_ac

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#1115]
**Item Count:** 500 items

**Item Types:** Image

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/aerial-photos-mid-willamette/aerial-photos-mid-willamette_ac.txt

**Parent:** #1112

**Comment by KevinJonesMeta** [comment]
QA pass. Ready for bulk review.

**Comment by wickr** [comment]
All reviewed and counts look good.
