### ISSUE TITLE
International Freshwater Treaties Collection (freshwater-treaties)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#1156]
**Item Count:** 656 items

**Item Types:** Document

**Access Restrictions:** 0

**Complex Objects:** 20

**pid List:** 
https://github.com/OregonDigital/OD2-migration/blob/master/freshwater-treaties/freshwater-treaties_nocpds.txt
https://github.com/OregonDigital/OD2-migration/blob/master/freshwater-treaties/freshwater-treaties_cpds.txt

**Comment by wickr** [comment]
PDFs fixed, derivatives looking good. Compounds have no errors. Only validation error left is on one with a Source field but the data is fine (verifier doesn't like the line break)

**Comment by carakey** [comment]
**QA** 

Overall:

- [ ] All works are migrated- original number of works and OD2 works match (Migration)
- [ ] Check that a minimum of 5 works are accessible in browse everything/all
- [ ] Check that a minimum of 5 works are accessible in by clicking on them in  browse everything/all
- [ ] If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible. 
- [ ] Confirm works are in the correct Admin set.

Search/indexing/faceting check:

- [ ] Works and collections appear in browse everything/all when searched with corresponding metadata
- [ ] Thumbnails are appearing for works; the collection has the correct icon.
- [ ] Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:
- [ ] Controlled and uncontrolled facets appear and are populated by data from works (When checking facets, check the core facets in the search results and the collection-specific facets on the collection homepage.)
- [ ] Labels are fetching correctly
- [ ] URIs are resolving correctly

Work pages: 
- [ ] The digital object(s) appear in viewer
- Files are attached
- Derivatives were created (both automated check from Migration and visual check from Metadeities)
- [ ] Metadata is also there in work and viewer
- Collection information is also on work page
- Confirm metadata is in IIIF viewer
- [ ] Linked Data:
- Labels are fetching correctly
- URIs are resolving correctly
- [ ] Download
- If high res download, double-check
- [ ] Copyright 
- Confirm copyright logo matches statement

Collection pages: 
- [ ] Collection pages are there
- [ ] Collection description/blurb is there
- [ ] Facets are there

- [ ] Restrictions: Double-check restricted collections and works (VPN)

- [ ] Bulk Approve (step 11)

- [ ] Collection-level QA: Compare number of assets on OD2 with total in original pidlist (step 12)

**Comment by carakey** [comment]
There is an issue with the Creator label on the URI http://id.loc.gov/authorities/names/n90718759 (label should be "Czech Republic" but instead showing some backend metadata: "Product of split:--Czech Republic--http://rdaregistry.info/Elements/u/P60685"), affecting show pages on 6 works.
I attempted to manually remove and re-add the URI on 9c67wr914 which did not correct the label.
Then noticed that the Data Sources tab is showing the label as expected, while the main show page has the error. This is true on the edited work and the non-edited ones.

**Comment by carakey** [comment]
The Geonames term 'Po River' in Water Basin is causing the same split-faceting issue we saw in cities in multiple counties. I reopened [2452](https://github.com/OregonDigital/OD2/issues/2452).

**Comment by carakey** [comment]
A couple of weird PDF mime types showing up. Maybe worth reprocessing and replacing the files.

![image](https://user-images.githubusercontent.com/17655103/224199979-5d2507ae-5ac5-456d-9974-a0584abdf8e1.png)

**Comment by carakey** [comment]
^ @wickr I will take a stab at the PDF replacement. I'm planning to move forward with item level QA otherwise, assuming these aren't migration issues but underlying system things.

**Comment by wickr** [comment]
Ok I fixed the Czech Republic label issue. Somehow that 'Product of split' string got included as another prefLabel at one point. I cleared out the blazegraph cache and refetched, and didn't see it come back. I reindexed all 8 works just to be sure and they're showing together now.

The PDF mpeg one is probably the only one I'd worry about for now, unless you want to do the EXIF one too, but that one might have EXIF metadata somewhere, so it's not really wrong.

Yeah I don't think anything else is migration-related.

**Comment by carakey** [comment]
thanks -- but what's the difference between `pdf (PDF/A)` (#2 with 28 works) and `pdf (PDF/A, Portable Document Format)` (#5 with 1 work)?

**Comment by wickr** [comment]
@carakey not sure. I'm sure we can collapse the values in indexing in the future, but so far we haven't messed with what is being extracted in characterization.

**Comment by carakey** [comment]
The 3 items whose PDFs I replaced, the thumbnails are not appearing on browse all / search results. The larger thumbnail is showing up ok on the (logged-in admin) work show page, and in the UV. 

https://oregondigital.org/concern/documents/gb19fs332
https://oregondigital.org/concern/documents/gb19fr191
https://oregondigital.org/concern/documents/gb19fq887

**Comment by carakey** [comment]
I noticed on a compound child, that the linked parent title has an unresolved character encoding showing -- "His Majesty&#39;s government..."
The encoding shows correctly in metadata and links elsewhere.

https://oregondigital.org/concern/documents/gb19fs528?locale=en

**Comment by carakey** [comment]
@wickr 

In addition to the thumbnail issue in an earlier comment, there are some inconsistencies with fileset downloads. Out of the set of 18 works that I approved for QA:

- 5 do not have any fileset downloads available (including all three where I replaced the PDF) - gb19fr191, gb19fs332, gb19fq887, gb19fm306, gb19fs528
- One compound parent has both high and standard quality downloads listed, but both sets of files are the same size - 9c67wr88t
- One compound parent has only the standard quality download listed, though both children have high quality downloads listed - 9c67wr914

Aside from these issues, things look good. Collection can be bulk approved once the filesets issues are fixed.

**Comment by wickr** [comment]
Reindexed all works that weren't showing thumbnails.

Made a ticket for the apostrophe entity reference showing: https://github.com/OregonDigital/OD2/issues/2861

Still looking at the download issues.

**Comment by wickr** [comment]
For the FileSets, for the 5 pids you linked, I'm seeing Download options showing up and working.

For the compound parents, I'm seeing both Standard and High Quality download options on both of them now. It's possible not all of the FileSets were indexed fully earlier.

I'm going to go ahead and bulk approve.

**Comment by wickr** [comment]
All works are reviewed and looking good. Counts look good too.

@carakey when you have a chance the collection homepage could use the 4 featured docs/thumbnails
