### ISSUE TITLE
oregon-multicultural-archives_ad

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#1166]
**Item Count:** 500 items

**Item Types:** Image/Document

**Access Restrictions:**

**Complex Objects:**

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/oregon-multicultural-archives/oregon-multicultural-archives_ad.txt

**Parent:** #1162

**Comment by KevinJonesMeta** [comment]
QA pass. Ready for bulk review.

**Comment by wickr** [comment]
All works are reviewed and counts look good, including the total OMA works count with works that were already ingested.
