### ISSUE TITLE
osu-scarc-gwil-evans_aa

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#1172]
**Item Count:** 500 items

**Item Types:** Image

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/osu-scarc-gwil-evans/osu-scarc-gwil-evans_aa.txt

**Parent:** #1171

**Comment by KevinJonesMeta** [comment]
QA pass. Ready for bulk review.

**Comment by wickr** [comment]
All works reviewed and counts look good.
