### ISSUE TITLE
easia_ac

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#134]
**Item Count:** 500 items

**Item Types:** Image/Document/Audio/Video

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/easia/easia_ac_pids
see https://github.com/OregonDigital/OD2-migration/issues/120

**Comment by lsat12357** [comment]
exported 20220626

**Comment by sseymore** [comment]
@lsat12357 https://oregondigital.org/catalog/oregondigital:df72d1181#page/1/mode/1up

Should we reupload? Please clarify.

**Comment by lsat12357** [comment]
yes, try fixing the pdf and uploading it directly into OD2. I've deleted the fileset.

**Comment by sseymore** [comment]
https://prod.oregondigital.org/concern/documents/df72d1181?locale=en gonna check back later to see if the derivs work

**Comment by lsat12357** [comment]
deleted fileset for df72d1181 again, rewrote the pdf using GhostScript and restarted fileset.
Looks ok now.
