### ISSUE TITLE
easia_ae

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#136]
**Item Count:** 500 items

**Item Types:** Image/Document/Audio/Video

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/easia/easia_ae_pids
see https://github.com/OregonDigital/OD2-migration/issues/120

**Comment by lsat12357** [comment]
exported 20220626

**Comment by sseymore** [comment]
@lsat12357 Is this work the only issue in this batch? https://oregondigital.org/catalog/oregondigital:df72db152#page/1/mode/1up Can you provide more detail on what we need to do to remediate?

**Comment by lsat12357** [comment]
I've deleted the fileset from df72db152. I suggest opening the pdf with acrobat, saving a new copy, and then trying to add it directly to the OD2 asset through the front end.

**Comment by sseymore** [comment]
Ok, once it's in OD2 I'll try this method to add the fileset to that work. I hope it works...

**Comment by sseymore** [comment]
https://prod.oregondigital.org/concern/documents/df72db152?locale=en waiting on derivs

**Comment by lsat12357** [comment]
ok, I deleted the fileset for df72db152 again, rewrote the pdf using GhostScript and restarted the fileset. Looks like it's finally working.
