### ISSUE TITLE
easia_af

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#137]
**Item Count:** 500 items

**Item Types:** Image/Document/Audio/Video

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/easia/easia_af_pids
see https://github.com/OregonDigital/OD2-migration/issues/120

**Comment by lsat12357** [comment]
exported 20220626

**Comment by sseymore** [comment]
https://oregondigital.org/catalog/oregondigital:df72dz137#page/1/mode/1up

@lsat12357 Do we need to reupload this PDF? Please clarify.

**Comment by lsat12357** [comment]
I have deleted the fileset from df72dz137. Try fixing the pdf and uploading directly into OD2

**Comment by sseymore** [comment]
https://prod.oregondigital.org/concern/documents/df72dz137?locale=en waiting for derivs

**Comment by lsat12357** [comment]
deleted fileset for df72dz137 again. rewrote pdf using GhostScript. restarted fileset. appears to be ok now
