### ISSUE TITLE
Oregon State Yank (oregon-state-yank)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#168]
**Item Count:** 8 items

**Item Types:** Document

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/oregon-state-yank/oregon-state-yank_pids.txt

**Comment by KevinJonesMeta** [comment]
QA Pass. I reviewed all 8 works.

**Comment by wickr** [comment]
All looks good.
