### ISSUE TITLE
Oregon's Agricultural Progress (oregons-agricultural-progress)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#169]
**Item Count:** 169 items

**Item Types:** Document

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/oregons-agricultural-progress/oregons-agricultural-progress_pids.txt

**Comment by wickr** [comment]
After some manual fixes, verification came back clean, with 1 exception: fx71c750q  there's a checksum error failing because it doesn't have the original File associated with the FileSet. But the file attached to the work on the second try and the derivatives work, so I'll move this forward while I investigate more.

**Comment by KevinJonesMeta** [comment]
**QA** 

Overall:

- [ ] All works are migrated- original number of works and OD2 works match (Migration)
- [ ] Check that a minimum of 5 works are accessible in browse everything/all
- [ ] Check that a minimum of 5 works are accessible in by clicking on them in  browse everything/all
- [ ] If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible. 
- [ ] Confirm works are in the correct Admin set.

Search/indexing/faceting check:

- [ ] Works and collections appear in browse everything/all when searched with corresponding metadata
- [ ] Thumbnails are appearing for works; the collection has the correct icon.
- [ ] Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:
- [ ] Controlled and uncontrolled facets appear and are populated by data from works (When checking facets, check the core facets in the search results and the collection-specific facets on the collection homepage.)
- [ ] Labels are fetching correctly
- [ ] URIs are resolving correctly

Work pages: 
- [ ] The digital object(s) appear in viewer
- Files are attached
- Derivatives were created (both automated check from Migration and visual check from Metadeities)
- [ ] Metadata is also there in work and viewer
- Collection information is also on work page
- Confirm metadata is in IIIF viewer
- [ ] Linked Data:
- Labels are fetching correctly
- URIs are resolving correctly
- [ ] Download
- If high res download, double-check
- [ ] Copyright 
- Confirm copyright logo matches statement

Collection pages: 
- [ ] Collection pages are there
- [ ] Collection description/blurb is there
- [ ] Facets are there

- [ ] Restrictions: Double-check restricted collections and works (VPN)

- [ ] Bulk Approve (step 11)

- [ ] Collection-level QA: Compare number of assets on OD2 with total in original pidlist (step 12)

**Comment by KevinJonesMeta** [comment]
Archival Folder Number (Folder Number in MAP) is populated on Oregon's Agricultural Progress works but does not appear in OD1 records. The Archival Folder Number displayed matches Number field (Has Number in MAP). This is true of Oregon State Yank records as well which I didn't catch during QA for that set. Not a migration issue per se but not desired behavior. Example: https://prod.oregondigital.org/concern/documents/fx71c7617

**Comment by KevinJonesMeta** [comment]
QA Pass (see note above). Ready for bulk approval.

**Comment by wickr** [comment]
With the has_number predicate fixed and deployed to production, I moved the values populated in folder_number to has_number (also got oregon-state-yank items). Everything is looking good.

**Comment by wickr** [comment]
Bulk reviewed. No updates to this collection.
