### ISSUE TITLE
C. L. Andrews photographs, 1880s-1948 (clarence-andrews)

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/OD2-migration#2]
Item Count: 41 items

Item Types: Image

Access Restrictions: 0

Complex Objects: 0

pid List:
https://github.com/OregonDigital/OD2-migration/blob/master/clarence-andrews/pids.txt

**Comment by lsat12357** [comment]
migration tasks:
- [ ] preflight
- [ ] export
- [ ] ingest
- [ ] verify

**Comment by sseymore** [comment]
waiting on https://github.com/OregonDigital/OD2/issues/1343 to be implemented to re-try QA process

**Comment by lsat12357** [comment]
[clarence-andrews_zips-assets-facet_report_20210205180650.txt](https://github.com/OregonDigital/OD2-migration/files/5954389/clarence-andrews_zips-assets-facet_report_20210205180650.txt)

**Comment by lsat12357** [comment]
[clarence-andrews_zips-totals-facet_report_20210205180650.txt](https://github.com/OregonDigital/OD2-migration/files/5954395/clarence-andrews_zips-totals-facet_report_20210205180650.txt)

**Comment by lsat12357** [comment]
[clarence-andrews_zips-totals-facet_report_20210210155603.txt](https://github.com/OregonDigital/OD2-migration/files/5959474/clarence-andrews_zips-totals-facet_report_20210210155603.txt)

**Comment by sseymore** [comment]
**QA** 

Overall:

- [ ] All works are migrated- original number of works and OD2 works match (Migration)
- [ ] Check that a minimum of 5 works are accessible in browse everything/all
- [ ] Check that a minimum of 5 works are accessible in by clicking on them in  browse everything/all
- [ ] If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible. 

Search/indexing/faceting check:

- [ ] Works and collections appear in browse everything/all when searched with corresponding metadata
- [ ] Thumbnails are also appearing for works and collections
- [ ] Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:
- [ ] Controlled and uncontrolled facets appear and are populated by data from works
- [ ] Labels are fetching correctly
- [ ] URIs are resolving correctly

Work pages: 
- [ ] The digital object(s) appear in viewer
- If files are attached
- Derivatives were created (both automated check from Migration and visual check from Metadeities)
- [ ] Metadata is also there in work and viewer
- Collection information is also on work page
- [ ] Linked Data:
- Labels are fetching correctly
- URIs are resolving correctly
- [ ] Download
- If high res download, double-check
- [ ] Copyright 

Collection pages: 
- [ ] Collection pages are there
- [ ] Collection description/blurb is there
- [ ] Facets are there

- [ ] Restrictions: Double-check restricted collections and works (VPN)

- [ ] Bulk Approve

- [ ] Collection-level QA: Compare number of assets on OD2 with total in original pidlist

**Comment by lsat12357** [comment]
preflight shows that crosswalk_overrides needs dateDigitized added (to be ignored)
