### ISSUE TITLE
Pacific Northwest Stream Survey (streamsurvey)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#216]
**Item Count:** 1,183 items

**Item Types:** Image/Document

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/streamsurvey/streamsurvey_pids.txt

**Comment by wickr** [comment]
I didn't forget to make batches on purpose, but I was pretty far along before I remembered. So probably good to do 10 items for QA on this one I think.

**Comment by carakey** [comment]
**QA** 

Overall:

- [ ] All works are migrated- original number of works and OD2 works match (Migration)
- [ ] Check that a minimum of 5 works are accessible in browse everything/all
- [ ] Check that a minimum of 5 works are accessible in by clicking on them in  browse everything/all
- [ ] If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible. 
- [ ] Confirm works are in the correct Admin set.

Search/indexing/faceting check:

- [ ] Works and collections appear in browse everything/all when searched with corresponding metadata
- [ ] Thumbnails are appearing for works; the collection has the correct icon.
- [ ] Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:
- [ ] Controlled and uncontrolled facets appear and are populated by data from works (When checking facets, check the core facets in the search results and the collection-specific facets on the collection homepage.)
- [ ] Labels are fetching correctly
- [ ] URIs are resolving correctly

Work pages: 
- [ ] The digital object(s) appear in viewer
- Files are attached
- Derivatives were created (both automated check from Migration and visual check from Metadeities)
- [ ] Metadata is also there in work and viewer
- Collection information is also on work page
- Confirm metadata is in IIIF viewer
- [ ] Linked Data:
- Labels are fetching correctly
- URIs are resolving correctly
- [ ] Download
- If high res download, double-check
- [ ] Copyright 
- Confirm copyright logo matches statement

Collection pages: 
- [ ] Collection pages are there
- [ ] Collection description/blurb is there
- [ ] Facets are there

- [ ] Restrictions: Double-check restricted collections and works (VPN)

- [ ] Bulk Approve (step 11)

- [ ] Collection-level QA: Compare number of assets on OD2 with total in original pidlist (step 12)

**Comment by carakey** [comment]
QA fail -- ONS Author labels are not fetching (noted on 4 documents). One document with an LC Author is fetching fine.
@wickr 

- - - - -
QA Notes

- 2 items were already approved when I began QA. Reviewed 10 additional items during QA process.
- Getting a lot of timeouts when trying to review individual works.
- I encountered a couple of Geonames labels that show up in OD2 that hadn't fetched in OD1. (Yay?)



**Not a migration issue per se:

- Dupes, df66qb40d & df66q970x
- Minor complaint that multiple Description fields are not ending up in the same order as in OD1; the "regular" description value is sometimes showing up after the "location notes" description value. This may be less readable especially given a lack of ending punctuation in either description value.

**Comment by wickr** [comment]
Updates to works in OD1 with Parkhurst URIs completed. Re-exported those and updated in OD2.

Deleted df66q970x in OD1, removed from pid list. Deleted OD2 object and FileSet (also migrator work).

Ran label verifier, looks good (yes some additional labels in OD2).

Descriptions aren't ordered in either system, Location Notes tend to show last but not always. Agree it's not a great look, would be solved with remediation but that's probably low priority.

**Comment by wickr** [comment]
Did a full reindex of the collection, which fixed the Witter number. However, there's a new label issue that's dropping labels for anything without a language specified, which is most of LCNAF, so Parkhurst is showing a URI.

**Comment by wickr** [comment]
@carakey I did another reindex and all the names look good now.

**Comment by carakey** [comment]
There are 6 works with Washington Water Power Company (http://id.loc.gov/authorities/names/n87836467) as a Subject; the URI was showing in the Topic facet, and neither URI nor Label was appearing on the work show page. I edited these 6 manually -- the form was able to find the correct term if I entered the URI with https instead of http. 

df66q2607
df66q278p
df66q259g
df66q2739
df66q274k
df66q2721

**Comment by carakey** [comment]
Another URI displaying in the facets, in Location this time. df66px88x had one of its Location values -- Clackamas River Scenic Waterway (https://sws.geonames.org/5719309) -- showing as the URI in the facet, and two out of three values were missing from the work show page. From the Data Sources tab, it looks like it was missing the ending slash '/' from the URI; not sure why two were affected on the show page. 

Fixed it manually (which was confusing and the form doesn't *quite* work as expected all the time...), seems ok now.

**Comment by carakey** [comment]
Institutions are mostly missing, too. The facet count for Institution is 24, should be 1183. Asking for a reindex.

**Comment by wickr** [comment]
Ok, fully reindexed again, the Institution labels got fixed.

**Comment by wickr** [comment]
I checked for more URIs in Location, found 1 on 2 works and corrected them.

**Comment by carakey** [comment]
This work has high-res available, but shouldn't https://prod.oregondigital.org/concern/images/df66px88x

**Comment by carakey** [comment]
Other than that funky high-res, QA pass. @wickr ready to bulk review

**Comment by wickr** [comment]
Bulk reviewed. Counts look good, and I don't see any more Full Size Download Allowed values.
