### ISSUE TITLE
building-or_ab

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#247]
**Item Count:** 500
**Item Types:** Image/Document
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/building-or/building-or_ab_pids
see https://github.com/OregonDigital/OD2-migration/issues/212

**Comment by lsat12357** [comment]
verification ok

**Comment by sseymore** [comment]
@lsat12357 Can you advise on next steps please so I can remediate? All of the images are loading in the viewers for me. Should I reupload these images?

**Comment by lsat12357** [comment]
I did not investigate the verifier's inability to run the checksum comparison, skipped bc the images looked ok
df67mk79p does not load, derivatives were created because of a minimagick error

**Comment by sseymore** [comment]
@lsat12357 Can we force the derivs locally? Do you know a way around this?

**Comment by lsat12357** [comment]
I downloaded the df67mk79p from OD1 and reuploaded through the OD2 GUI. seems to have completed.
