### ISSUE TITLE
building-or_ac

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#248]
**Item Count:** 500
**Item Types:** Image/Document
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/building-or/building-or_ac_pids
see https://github.com/OregonDigital/OD2-migration/issues/212

**Comment by lsat12357** [comment]
verification ok

**Comment by sseymore** [comment]
Trying to find this image. Pause for now.

**Comment by sseymore** [comment]
@lsat12357 File never existed. @jsimic delete? From Andy:

<img width="434" alt="Screen Shot 2023-01-05 at 8 57 33 AM" src="https://user-images.githubusercontent.com/7328774/210837293-bb36a52a-3f7e-4801-a2a3-a2f1136af2cf.png">

**Comment by jsimic** [comment]
@sseymore  Delete! Delete!

**Comment by lsat12357** [comment]
deleted from OD1
