### ISSUE TITLE
building-or_bt

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#290]
**Item Count:** 500
**Item Types:** Image/Document
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/building-or/building-or_bt_pids
see https://github.com/OregonDigital/OD2-migration/issues/212

**Comment by lsat12357** [comment]
verification
df70jf110 does not have an image on od1

**Comment by jsimic** [comment]
@lsat12357 Kill it!

**Comment by lsat12357** [comment]
df70jf110 reexported, but the model on OD1 must still be set to Generic rather than Image, so the migration failed.
deleted for the 2nd time, manually updated the migrator work to have model=Image and migration restarted.
df70jf110 is ok except for there are a number of creators which don't have labels fetched; they seem to all be opaquenamespace uris, and the first one does not exist...
ok for now?

**Comment by sseymore** [comment]
@lsat12357 yeah, move it forward. I'll work on the URIs.
