### ISSUE TITLE
Minorities and LGBTQ+ Histories in the Barometer

### ISSUE THREAD

**Issue by KevinJonesMeta** [OregonDigital/OD2-migration#3]
**Item Count:** 40 items

**Item Types:** Document

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/minorities-lgbtq-barometer/pids.txt

**Comment by lsat12357** [comment]
see https://github.com/OregonDigital/oregondigital/issues/1405

**Comment by sseymore** [comment]
**QA** 

Overall:

- [ ] All works are migrated- original number of works and OD2 works match (Migration)
- [ ] Check that a minimum of 5 works are accessible in browse everything/all
- [ ] Check that a minimum of 5 works are accessible in by clicking on them in  browse everything/all
- [ ] If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible. 

Search/indexing/faceting check:

- [ ] Works and collections appear in browse everything/all when searched with corresponding metadata
- [ ] Thumbnails are also appearing for works and collections
- [ ] Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:
- [ ] Controlled and uncontrolled facets appear and are populated by data from works
- [ ] Labels are fetching correctly
- [ ] URIs are resolving correctly

Work pages: 
- [ ] The digital object(s) appear in viewer
- If files are attached
- Derivatives were created (both automated check from Migration and visual check from Metadeities)
- [ ] Metadata is also there in work and viewer
- Collection information is also on work page
- [ ] Linked Data:
- Labels are fetching correctly
- URIs are resolving correctly
- [ ] Download
- If high res download, double-check
- [ ] Copyright 

Collection pages: 
- [ ] Collection pages are there
- [ ] Collection description/blurb is there
- [ ] Facets are there

- [ ] Restrictions: Double-check restricted collections and works (VPN)

- [ ] Bulk Approve

- [ ] Collection-level QA: Compare number of assets on OD2 with total in original pidlist

**Comment by lsat12357** [comment]
latest round of config fixes have this coll passing verification again.

**Comment by KevinJonesMeta** [comment]
QA

Overall:

- [ ]  All works are migrated- original number of works and OD2 works match (Migration)

- [ ]  Check that a minimum of 5 works are accessible in browse everything/all

- [ ]  Check that a minimum of 5 works are accessible in by clicking on them in browse everything/all

- [ ]  If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible.

Search/indexing/faceting check:

 

- [ ] Works and collections appear in browse everything/all when searched with corresponding metadata

 

- [ ] Thumbnails are also appearing for works and collections

 

- [ ] Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:

- [ ]  Controlled and uncontrolled facets appear and are populated by data from works

- [ ]  Labels are fetching correctly

- [ ]  URIs are resolving correctly

Work pages:

- [ ]  The digital object(s) appear in viewer

If files are attached
Derivatives were created (both automated check from Migration and visual check from Metadeities)

- [ ]  Metadata is also there in work and viewer

Collection information is also on work page

- [ ]  Linked Data:

Labels are fetching correctly
URIs are resolving correctly
 

- [ ] Download

If high res download, double-check

- [ ]  Copyright

Collection pages:

 

- [ ] Collection pages are there

- [ ]  Collection description/blurb is there

- [ ]  Facets are there

- [ ]  Restrictions: Double-check restricted collections and works (VPN)

- [ ]  Bulk Approve

 

- [ ] Collection-level QA: Compare number of assets on OD2 with total in original pidlist

**Comment by KevinJonesMeta** [comment]
QA Pass?

-Data appears to be in OD2 staging but not necessarily utilized by system as expected in a few cases.

Notes:
-Keyword search for "Minorities Barometer" gets expected results including collection and reviewed works.
-Keyword search for "Minorities and LGBTQ Histories in the Barometer" or "Minorities and LGBTQ+ Histories in the Barometer" does not return collection and only partial list of expected works.
-This collection does not have a description blurb
-Facets are missing from collection page
-This collection does not have restrictions
-Bulk approve is not available in dashboard
