### ISSUE TITLE
Lincoln County Historical Society Archive (lchsa)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#352]
**Item Count:** 1,393 items

**Item Types:** Image

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** 
https://github.com/OregonDigital/OD2-migration/blob/master/lchsa/lchsa_aa.txt
https://github.com/OregonDigital/OD2-migration/blob/master/lchsa/lchsa_ab.txt
https://github.com/OregonDigital/OD2-migration/blob/master/lchsa/lchsa_ac.txt

**Comment by carakey** [comment]
All batches QA'd

**Comment by wickr** [comment]
All reviewed and counts look good.
