### ISSUE TITLE
uo-arch-photos_ch_am

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#421]
**Item Count:** 500
**Item Types:** Image/Document
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/uo-arch-photos/uo-arch-photos_ch_am_pids
see https://github.com/OregonDigital/OD2-migration/issues/400

**Comment by lsat12357** [comment]
verification
run fix_fileset df72td91c

**Comment by sseymore** [comment]
@lsat12357  https://oregondigital.org/catalog/oregondigital:df72td91c Reuploaded image and it looks good to me. Try again?

**Comment by lsat12357** [comment]
df72td91c reexported, fileset redone
verification ok
