### ISSUE TITLE
uo-arch-photos_ch_bs

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#453]
**Item Count:** 500
**Item Types:** Image/Document
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/uo-arch-photos/uo-arch-photos_ch_bs_pids
see https://github.com/OregonDigital/OD2-migration/issues/400

**Comment by lsat12357** [comment]
fix df727p956 df66nj32m

**Comment by sseymore** [comment]
@lsat12357

What's wrong with? https://oregondigital.org/catalog/oregondigital:df727p956 Seeing the image in the viewer on my end. 

https://oregondigital.org/catalog/oregondigital:df66nj32m I reuploaded the image and it's working on my end. Try again?
