### ISSUE TITLE
uo-arch-photos_ch_bt

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#454]
**Item Count:** 500
**Item Types:** Image/Document
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/uo-arch-photos/uo-arch-photos_ch_bt_pids
see https://github.com/OregonDigital/OD2-migration/issues/400

**Comment by lsat12357** [comment]
fix filesets df727891m, df66nm275, df73gg52h

**Comment by sseymore** [comment]
@lsat12357 

https://oregondigital.org/catalog/oregondigital:df727891m Reuploaded image and working on my end. Try again?
