### ISSUE TITLE
uo-arch-photos_ch_bw

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#457]
**Item Count:** 500
**Item Types:** Image/Document
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/uo-arch-photos/uo-arch-photos_ch_bw_pids
see https://github.com/OregonDigital/OD2-migration/issues/400

**Comment by lsat12357** [comment]
fix df72tf08b

**Comment by sseymore** [comment]
@lsat12357 https://oregondigital.org/catalog/oregondigital:df72tf08b I re-uploaded this image. Working on my end. Try again?

**Comment by lsat12357** [comment]
df72tf08b reexported, fileset restarted
verification ok
