### ISSUE TITLE
mss-rb_ch_ad

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#586]
**Item Count:** 500
**Item Types:** Image/Document/Generic
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/mss-rb/mss-rb_ch_ad_pids
see https://github.com/OregonDigital/OD2-migration/issues/582

**Comment by lsat12357** [comment]
6h440w21b fixed rights, reexport and update
6h440w181 fixed rights, reexport and update
df7361205 retry derivs
bv73c197d does not exist on od1
6h440w245 fixed rights, reexport and update
6h440w47g fixed rights, reexport and update
6h440w202 fixed rights, reexport and update

**Comment by sseymore** [comment]
@lsat12357 

bv73c197d: Does on exist on OD1, so don't migrate.

https://oregondigital.org/sets/mss-rb/oregondigital:df7361205 @jsimic Migrated from CDM. I can't find the images on Archived Projects. Can you look?

**Comment by sseymore** [comment]
@lsat12357 

bv73c197d: Does not exist on OD1 so don't migrate.

https://oregondigital.org/catalog/oregondigital:df7361205 Found and reuploaded image. Let me know if this doesn't work. 

Does that cover it for this batch? Please let me know.

**Comment by lsat12357** [comment]
df7361205 reexported and redid fileset. verification ok
