### ISSUE TITLE
mss-rb_ch_ae

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#587]
**Item Count:** 500
**Item Types:** Image/Document/Generic
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/mss-rb/mss-rb_ch_ae_pids
see https://github.com/OregonDigital/OD2-migration/issues/582

**Comment by lsat12357** [comment]
6h440w377 fixed rights
df736148v retry derivs
bv73c2065 does not exist on od1
bv73c6060 fix all
6h440w35p fixed rights
6h440w41t fixed rights
bv73c2022 does not exist on od1

**Comment by sseymore** [comment]
@lsat12357 

bv73c2065: Does not exist on OD1 so don't migrate.

bv73c2022: Does not exist on OD1 so don't migrate.

https://oregondigital.org/sets/mss-rb/oregondigital:df736148v: @jsimic Migrated from CDM. I can't find the images on Archived Projects. Can you look?

**Comment by sseymore** [comment]
https://oregondigital.org/sets/mss-rb/oregondigital:df736148v

Nevermind @jsimic I found it and reuploaded. @lsat12357 Let me know if this works and if there's anything else I need to do for this batch.

**Comment by lsat12357** [comment]
df736148v reexported, fileset redone. verification ok
