### ISSUE TITLE
Oregon State University Fact Books (osu-fact-book)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#620]
**Item Count:** 13 items

**Item Types:** Document

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/osu-fact-book/osu-fact-book_pids.txt

**Comment by KevinJonesMeta** [comment]
QA pass. Collection page does not have description. I will contact curator about text for a description. Publication Place label issue present in collection. Ready for bulk review.

**Comment by KevinJonesMeta** [comment]
Collection description has been added.

**Comment by wickr** [comment]
Bulk approved previously. Reindexed all works just now to get location label fix for Publication Place. Everything looks good.
