### ISSUE TITLE
mss-rb_cpd

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#625]
**Item Count:** 106 items

**Item Types:** Generic

**Access Restrictions:**

**Complex Objects:** 106

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/mss-rb/mss-rb_cpd_pids
see https://github.com/OregonDigital/OD2-migration/issues/582

**Comment by lsat12357** [comment]
df67wq320 uses table_of_contents, which is on the map, but not completely configured for Generic on OD2
kp78hq90w fixed backslash in description, reexported and rerunning 
bv73c787d does not exist on od1
otherwise, mass carnage on fetch labels. most will hopefully be resolved when I run the lci fix and most things are indexed again

**Comment by sseymore** [comment]
@lsat12357 

bv73c787d - Doesn't exist on OD1 so don't migrate. Guessing it was deleted on OD1 on purpose. 

Trying to see if threre's anything else we need to do here. Can you let me know?

**Comment by lsat12357** [comment]
looks like df67wq320 table of contents

**Comment by sseymore** [comment]
@lsat12357 This is not ideal, but I want to move this along without changing the Hyrax code for now. I moved that data to a description field.

**Comment by lsat12357** [comment]
verification ok for df67wq320
