### ISSUE TITLE
ken-gray_aa

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#634]
**Item Count:** 500 items

**Item Types:** Image

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/ken-gray/ken-gray_aa.txt

**Parent:**
https://github.com/OregonDigital/OD2-migration/issues/633

**Comment by KevinJonesMeta** [comment]
QA pass. Ready for bulk review.

**Comment by wickr** [comment]
Reviewed and whole collection looks good.
