### ISSUE TITLE
Chuck Williams Photographs (chuck-williams)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#756]
**Item Count:** 54 items

**Item Types:** Image

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/chuck-williams/chuck-williams_pids.txt

**Comment by wickr** [comment]
Collection was missed in admin set crosswalk so it needs to be added before ingest can happen. The collection also needs to be created in OD2.

**Comment by wickr** [comment]
https://github.com/OregonDigital/OD2/pull/2530

**Comment by KevinJonesMeta** [comment]
**QA** 

Overall:

- [ ] All works are migrated- original number of works and OD2 works match (Migration)
- [ ] Check that a minimum of 5 works are accessible in browse everything/all
- [ ] Check that a minimum of 5 works are accessible in by clicking on them in  browse everything/all
- [ ] If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible. 
- [ ] Confirm works are in the correct Admin set.

Search/indexing/faceting check:

- [ ] Works and collections appear in browse everything/all when searched with corresponding metadata
- [ ] Thumbnails are appearing for works; the collection has the correct icon.
- [ ] Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:
- [ ] Controlled and uncontrolled facets appear and are populated by data from works (When checking facets, check the core facets in the search results and the collection-specific facets on the collection homepage.)
- [ ] Labels are fetching correctly
- [ ] URIs are resolving correctly

Work pages: 
- [ ] The digital object(s) appear in viewer
- Files are attached
- Derivatives were created (both automated check from Migration and visual check from Metadeities)
- [ ] Metadata is also there in work and viewer
- Collection information is also on work page
- Confirm metadata is in IIIF viewer
- [ ] Linked Data:
- Labels are fetching correctly
- URIs are resolving correctly
- [ ] Download
- If high res download, double-check
- [ ] Copyright 
- Confirm copyright logo matches statement

Collection pages: 
- [ ] Collection pages are there
- [ ] Collection description/blurb is there
- [ ] Facets are there

- [ ] Restrictions: Double-check restricted collections and works (VPN)

- [ ] Bulk Approve (step 11)

- [ ] Collection-level QA: Compare number of assets on OD2 with total in original pidlist (step 12)

**Comment by KevinJonesMeta** [comment]
QA fail. Collection metadata does not appear on works but does appear in viewer. Collection page does not have description or facets.

**Comment by KevinJonesMeta** [comment]
I added description to collection page from OD1 but has some format issues for the Acknowledgements section.

**Comment by KevinJonesMeta** [comment]
QA Pass. Collection appears on works. Collection page needs facets.

**Comment by wickr** [comment]
Batch reviewed. Counts and facets look good.

For now I combined the Description fields, moving Acknowledgements to the bottom of the main one. Doesn't directly address the formatting issues. But since we can't control order, I was seeing the Acknowledgements block show as the main Collection blurb, so this resolves that.
