### ISSUE TITLE
aa-images_fc_nv

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#811]
**Item Count:** 500
**Item Types:** Image
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/aa-images_abc/aa-images_fc_pids
see https://github.com/OregonDigital/OD2-migration/issues/646

**Comment by lsat12357** [comment]
df71qd66c does not appear to have a content file on OD1

**Comment by sseymore** [comment]
Trying to find this image. Pause for now.

**Comment by sseymore** [comment]
@lsat12357 Uploaded image. Ready to try again.

**Comment by lsat12357** [comment]
df71qd66c reexported and migrated. item did not migrate first time around, as it was exported as generic (no content file), and OD2 would not ingest a generic asset with the view property. Manually edited the model to be 'Image'  on the migrator work.
verification ok, see grandparent ticket for list of label fetch issues to be addressed.
