### ISSUE TITLE
aa-images_fs_nv

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/OD2-migration#827]
**Item Count:** 500
**Item Types:** Image
**pid List** https://github.com/OregonDigital/OD2-migration/blob/master/aa-images_abc/aa-images_fs_pids
see https://github.com/OregonDigital/OD2-migration/issues/646

**Comment by lsat12357** [comment]
df71qd68x has no content file on OD1

**Comment by sseymore** [comment]
Trying to find this image. Pause for now.

**Comment by sseymore** [comment]
@lsat12357 Uploaded image. Ready to try again.

**Comment by lsat12357** [comment]
df71qd68x reexported and migration restarted. edited model to be 'Image.' 
verification ok, see grandparent ticket for issues with fetching labels
