### ISSUE TITLE
Braceros in Oregon Photograph Collection (braceros)

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2-migration#90]
**Item Count:** 100 items

**Item Types:** Image

**Access Restrictions:** 0

**Complex Objects:** 0

**pid List:** https://github.com/OregonDigital/OD2-migration/blob/master/braceros/braceros_pids

**Comment by wickr** [comment]
Ingest failed.
` <http://opaquenamespace.org/ns/full> "fullres\P120_2790.tif" ` 
backslash is causing problems. Going to remediate on OD1 and redo export.

**Comment by wickr** [comment]
Re-exported, after Ingest, 8 were successful. The rest failed with error: 
"error while persisting work: Term not in controlled vocabulary: http://www.w3.org/2000/01/rdf-schema#Class"

Due to 
```<http://purl.org/dc/dcmitype/Image> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> .```

**Comment by wickr** [comment]
2nd Ingest try had all but 1 be successful. The pid of the work that was missing had been taken by a test collection that Corey made. There wasn't an error in the migrator, though when running the VerifyWorkJob job it failed since there's no `admin_set_id` on a Collection. I destroyed the Collection, and then deleted the tombstone from Fedora. That freed up the pid, and the last work ingested fine after that.

**Comment by wickr** [comment]
100 works now in and verified.

**Comment by KevinJonesMeta** [comment]
**QA** 

Overall:

- [ ] All works are migrated- original number of works and OD2 works match (Migration)
- [ ] Check that a minimum of 5 works are accessible in browse everything/all
- [ ] Check that a minimum of 5 works are accessible in by clicking on them in  browse everything/all
- [ ] If collections have different Hyrax types (Documents, Images, Video, Audio, etc.), check 5 of each type, if possible. 
- [ ] Confirm works are in the correct Admin set.

Search/indexing/faceting check:

- [ ] Works and collections appear in browse everything/all when searched with corresponding metadata
- [ ] Thumbnails are appearing for works; the collection has the correct icon.
- [ ] Keyword searching appears in browse everything/all and keywords in title, description, full text appear with hit highlighting for works and collections

Facets:
- [ ] Controlled and uncontrolled facets appear and are populated by data from works (When checking facets, check the core facets in the search results and the collection-specific facets on the collection homepage.)
- [ ] Labels are fetching correctly
- [ ] URIs are resolving correctly

Work pages: 
- [ ] The digital object(s) appear in viewer
- Files are attached
- Derivatives were created (both automated check from Migration and visual check from Metadeities)
- [ ] Metadata is also there in work and viewer
- Collection information is also on work page
- Confirm metadata is in IIIF viewer
- [ ] Linked Data:
- Labels are fetching correctly
- URIs are resolving correctly
- [ ] Download
- If high res download, double-check
- [ ] Copyright 
- Confirm copyright logo matches statement

Collection pages: 
- [ ] Collection pages are there
- [ ] Collection description/blurb is there
- [ ] Facets are there

- [ ] Restrictions: Double-check restricted collections and works (VPN)

- [ ] Bulk Approve (step 11)

- [ ] Collection-level QA: Compare number of assets on OD2 with total in original pidlist (step 12)

**Comment by wickr** [comment]
Bulk approved, everything looks good. No change in status to OD1 items.
